# Generated by Django 4.1.1 on 2023-05-06 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('emp_priority', models.CharField(max_length=20)),
                ('emp_task_name', models.CharField(max_length=50)),
                ('emp_due_date', models.DateField()),
                ('emp_description', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
