# Generated by Django 4.1.1 on 2023-05-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_emp_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='emp_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
